### ISSUE TITLE
Player cannot respawn and reconnect: NullPointerException

### ISSUE THREAD

**Issue by RisingInIris2017** [FTBTeam/FTB-Library-Legacy#85]
#### Mod version:

ftblib-5.4.4.5

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:

Multiplayer, using Forge.

#### Installed mods:
![](https://user-images.githubusercontent.com/28519848/72771245-41a08f80-3c3b-11ea-9b29-d0f190d22eab.jpg)

## Link to full server log
https://paste.ubuntu.com/p/72nkYJnd6G/

## Description of the problem
There is a player whose ID is kanying. Every time he is killed, he cannot respawn.
He clicked the "Respawn" button on the respawn screen again and again, which is of no use.
I checked the log file I have provided above, and found that when he was killed,
server thrown a NullPointerException.
This is a part from the log provided above, from Line 4639 to Line 4706:
> [21:33:11] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: kanying[/39.144.17.96:45195] logged in with entity id 120519 at (187.52534310260518, 43.0, -670.3937377272149)
[21:33:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: kanying joined the game
[21:33:11] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@14306f:
java.lang.NullPointerException: QIANSG is not online!
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getPlayer(ForgePlayer.java:265) ~[ForgePlayer.class:?]
	at com.feed_the_beast.ftbutilities.data.FTBUtilitiesPlayerData.clearCache(FTBUtilitiesPlayerData.java:316) ~[FTBUtilitiesPlayerData.class:?]
	at com.feed_the_beast.ftblib.lib.data.NBTDataStorage.clearCache(NBTDataStorage.java:123) ~[NBTDataStorage.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.clearCache(ForgePlayer.java:105) ~[ForgePlayer.class:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_181]
	at com.feed_the_beast.ftblib.lib.data.Universe.clearCache(Universe.java:842) ~[Universe.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.onLoggedIn(ForgePlayer.java:368) ~[ForgePlayer.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.onPlayerLoggedIn(Universe.java:640) ~[Universe.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.onPlayerLoggedIn(Universe.java:161) ~[Universe.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_Universe_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219) [pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[21:33:11] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[21:33:11] [Server thread/ERROR] [FML]: 0: NORMAL
[21:33:11] [Server thread/ERROR] [FML]: 1: ASM: forge playerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 2: ASM: class com.feed_the_beast.ftblib.lib.data.Universe onPlayerLoggedIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 3: ASM: vazkii.quark.tweaks.feature.AutomaticRecipeUnlock@2123b85 onPlayerLoggedIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 4: ASM: vazkii.quark.management.gamerule.DropoffGamerule@2bf95ef5 login(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 5: ASM: forestry.core.EventHandlerCore@f9a431b handlePlayerLoggedIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 6: ASM: forestry.mail.EventHandlerMailAlert@4a5843c8 handlePlayerLoggedIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 7: ASM: forestry.book.EventHandlerBook@19e02405 onPlayerLoggedIn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 8: ASM: class vazkii.patchouli.common.handler.AdvancementSyncHandler onLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 9: ASM: cofh.thermalexpansion.proxy.EventHandler@4e4d0726 handlePlayerLoggedInEvent(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/ERROR] [FML]: 10: ASM: class thebetweenlands.common.handler.PlayerJoinWorldHandler onPlayerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[21:33:11] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /39.144.17.96:45195
java.lang.NullPointerException: QIANSG is not online!
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getPlayer(ForgePlayer.java:265) ~[ForgePlayer.class:?]
	at com.feed_the_beast.ftbutilities.data.FTBUtilitiesPlayerData.clearCache(FTBUtilitiesPlayerData.java:316) ~[FTBUtilitiesPlayerData.class:?]
	at com.feed_the_beast.ftblib.lib.data.NBTDataStorage.clearCache(NBTDataStorage.java:123) ~[NBTDataStorage.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.clearCache(ForgePlayer.java:105) ~[ForgePlayer.class:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_181]
	at com.feed_the_beast.ftblib.lib.data.Universe.clearCache(Universe.java:842) ~[Universe.class:?]
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.onLoggedIn(ForgePlayer.java:368) ~[ForgePlayer.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.onPlayerLoggedIn(Universe.java:640) ~[Universe.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.onPlayerLoggedIn(Universe.java:161) ~[Universe.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_Universe_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[21:33:11] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: kanying lost connection: Internal server error
[21:33:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: kanying left the game

I thought this issue might be related to FTBLib, so I posted this issue here.
I hope I would get your help.

Look forward to your reply!
Thanks in advance!

**Comment by klaoude** [comment]
Hi, i had the same error as you. I found a ugly fix.
I replace in the com.frrd_the_beast.ftblib.lib.data.ForgePlayer.java file the function getPlayer.
I change the line 255 "throw new NullPointerException(getName() + " is not online!");" with "return null;"
I know it's very ugly but meh, it works

If someone found a better fix i'll take it.
